e2e tests added
redhat-developer/podman-desktop-sandbox-ext pull request #210
Opened 2024-10-08 00:47 UTC by xbabalov

Added e2e tests that cover extension installation and handling.

2024-10-10 08:25 UTC, jeffmaury requested changes
Also needs rebase

2024-10-10 08:25 UTC, jeffmaury commented on package.json
> +    "node-fetch": "^2.6.1"
Should be in devDependencies ?

2024-10-15 11:04 UTC, odockal requested changes
Quite ok, except the review comments. but e2e tests are overal ok!

2024-10-15 11:04 UTC, odockal commented on vitest.config.js
> +      exclude: ['tests/**', '**/builtin/**',
this is coverage part. We should not touch coverage, we might add `tests` folder though here.

2024-10-15 11:04 UTC, odockal commented on vitest.config.js
>        include: ['**/*.ts'],
WE may explicitly include unit tests (omitting e2e tests), see here: https://github.com/redhat-developer/podman-desktop-redhat-account-ext/blob/main/vitest.config.js#L66

2024-10-15 11:04 UTC, odockal commented on package.json
>      "format:check": "prettier --check \"**/*.ts\" \"scripts/*.js\"",
if you change name of the script `build.js` -> `build.cjs` it also needs to be reflected here.

2024-10-15 11:04 UTC, odockal commented on tests/src/developer-sandbox.spec.ts
> +      test.skip(extensionInstalled && !skipInstallation);
this condition needs to be rewritten into: `!!skipInstallation` otherwise it does not work as expected in PR check.

2024-10-16 08:53 UTC, odockal approved these changes

2024-10-16 12:12 UTC, jeffmaury requested changes
Such a PR should be split in 2 parts: switch to module then add E2E tests

2024-10-18 05:43 UTC, odockal commented
@jeffmaury @xbabalov First we need to switch to ES modules and then we could merge this PR. I will open an issue.

2024-10-18 05:49 UTC, odockal commented
@xbabalov please open a PR to fix https://github.com/redhat-developer/podman-desktop-sandbox-ext/issues/219 which changes related to switch to ES modules.

2024-10-22 23:47 UTC, xbabalov commented
https://github.com/redhat-developer/podman-desktop-sandbox-ext/pull/221 was merged, I rebased and updated the files, so this should be ready for merge as well.

2024-10-23 08:34 UTC, odockal approved these changes
LGTM

2024-10-23 09:33 UTC, jeffmaury commented on package.json
> +    "node-fetch": "^2.6.1"
node-fetch is to be removed as fetch is now native since fetch is now part of nodejs

2024-10-29 12:07 UTC, jeffmaury commented on package.json
> +    "got": "^14.4.2"
Why did got version get lowered ?

2024-10-29 12:07 UTC, jeffmaury commented on package.json
> +    "@podman-desktop/tests-playwright": "next",
Not sure we should use next as it is unreliable

2024-10-29 13:29 UTC, odockal commented on package.json
> +    "@podman-desktop/tests-playwright": "next",
I think it is ok. We are replacing it with latest in the CI. Otherwise it gets latest stable released version of the package in lock file.

2024-10-30 15:55 UTC, jeffmaury approved these changes
LGTM

2024-10-30 19:22 UTC, odockal commented
@xbabalov @jeffmaury Thanks!

2024-10-30 19:23 UTC, merged